image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.5.0

stages:
  - mvn-package
  - maven-deploy

maven-test-branches:
  stage: mvn-package
  script:
    - git_merge develop
    - mvn package source:jar-no-fork javadoc:jar -DskipTests=false
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=${SONAR_URL} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME} -Dsonar.gitlab.project_id=${CI_PROJECT_ID}
  only:
    - branches
  except:
    - master
    - tags
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/

maven-deploy-choerodon:
  stage: maven-deploy
  script:
    - mvn clean install -DskipTests=true deploy -DaltDeploymentRepository=${CHOERODON_REPOSITORY_ID}::default::${CHOERODON_REPOSITORY_URL}
  only:
    - master
    - develop
    - tags
    - /^release-.*$/

maven-deploy-ossrh:
  stage: maven-deploy
  script:
    - mvn clean source:jar-no-fork javadoc:jar install -DskipTests=true gpg:sign deploy -DaltDeploymentRepository=${OSS_REPOSITORY_ID}::default::${OSS_REPOSITORY_URL} -DpomFile=pom.xml
  only:
    - tags

.auto_devops: &auto_devops |
    curl -o .auto_devops.sh \
        "${CHOERODON_URL}/devops/ci?token=${Token}&type=lib"
    source .auto_devops.sh

    function git_merge(){
        git config user.name ${GITLAB_USER_NAME}
        git config user.email ${GITLAB_USER_EMAIL}
        git checkout origin/${1:-"develop"}
        git merge ${CI_COMMIT_SHA} --no-commit --no-ff
    }

before_script:
  - *auto_devops
